# Site settings
title: Gtk-rs
description: > # this means to ignore newlines until "baseurl:"
  Rust bindings for GTK+ and GLib-based libraries
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gtk-rs.org" # the base hostname & protocol for your site
github_username: gtk-rs
permalink: /blog/:year/:month/:day/:title.html
authors:
  gkoz: '<a href="https://github.com/gkoz">Gleb Kozyrev</a>'

# Build settings
markdown: kramdown
